### ISSUE TITLE
Server Crash: java.lang.NoSuchMethodError: Ljava/lang/String;

### ISSUE THREAD

**Issue by Krutoy242** [YakosWG/PortableDrill#3] opened 2021-01-05 18:28 UTC
I installed `portabledrill-1.2`. Its working fine on client, but when i lunch separated server, it crushes with error:
```java
[21:20:26] [Server thread/ERROR] [net.minecraft.server.MinecraftServer]: Encountered an unexpected exception
java.lang.NoSuchMethodError: net.minecraft.creativetab.CreativeTabs.func_78013_b()Ljava/lang/String;
	at yako.portabledrill.items.ItemDrill.func_150895_a(ItemDrill.java:164) ~[ItemDrill.class:?]
	at crafttweaker.mc1120.item.MCItemUtils.createItemList(MCItemUtils.java:53) ~[MCItemUtils.class:?]
	at crafttweaker.mc1120.brackets.BracketHandlerItem.rebuildItemRegistry(BracketHandlerItem.java:64) ~[BracketHandlerItem.class:?]
	at crafttweaker.mc1120.events.CommonEventHandler.registerRecipes(CommonEventHandler.java:62) ~[CommonEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1345_CommonEventHandler_registerRecipes_Register.invoke(.dynamic) ~[?:?]
```

I thought this somehow connected with changing recipes, but removing script lines that changing the drill recipe wont help.

[debug.log.gz](https://github.com/YakosWG/PortableDrill/files/5771905/debug.log.gz)

**Comment by YakoSWG** [comment] 2021-01-11 17:25
Can you send me a list of the mods you were using? I can't reproduce the crash. Maybe send me the crash log as well. Considering it works on client this might be an issue with sidedness. I changed one line that might fix it. If you're comfortable with downloading from mediafire here's a [link](https://www.mediafire.com/file/0kbyxg667pymd7a/portabledrill-1.2.jar/file)

**Comment by Krutoy242** [comment] 2021-01-12 08:56
> I changed one line that might fix it. If you're comfortable with downloading from mediafire here's a [link](https://www.mediafire.com/file/0kbyxg667pymd7a/portabledrill-1.2.jar/file)

Yes, it works! Server loaded fine with this file. Seems like problem is fixed.

> Can you send me a list of the mods you were using? 
> Maybe send me the crash log as well.

I did both already. First message had [debug.log.gz](https://github.com/YakosWG/PortableDrill/files/5771905/debug.log.gz) that content both mod list and crush report.

Just in case, fresh log (with new file, without crash): [debug.log](https://github.com/YakosWG/PortableDrill/files/5800882/debug.log)

**Comment by YakoSWG** [comment] 2021-01-12 14:37
I suppose that's fixed now. Thanks for reporting!

**Closed as completed by YakoSWG** 2021-01-12 14:37 UTC
Labels: bug
